Repository openpubkey/openpubkey, pull requests merged in 2024-04, with the labels that each got.

#171 Adds a compact representation of a PK Token
  oidc/oidc.go
  pktoken/compact.go
  pktoken/compact_test.go
  pktoken/pktoken.go
  pktoken/pktoken_test.go
Labels: enhancement

#174 Adds apache2 license to all files
  cosigner/cosignerverifier.go
  discover/discover.go
  examples/ssh/opkssh/cli_test.go
  examples/ssh/opkssh/policy.go
  examples/ssh/sshcert/sshcert.go
  examples/ssh/sshcert/sshcert_test.go
  gq/benchmark_test.go
  gq/bigutil.go
  gq/gq_iso_test.go
  gq/rsa.go
  gq/sign.go
  gq/verify.go
  pktoken/clientinstance/claims.go
  providers/test.go
  util/base64.go
  util/bytes.go
  util/launch.go
Labels: documentation

#177 feat: Adds JKT (thumprint) to Protected Header of GQ Signed ID Tokens
  client/opkclient_test.go
  examples/gitlab/example_test.go
  examples/simple/example_test.go
  examples/x509/example_test.go
  oidc/sig.go
  pktoken/mocks/pktoken.go
  providers/gq.go
  providers/gq_test.go
  providers/mockprovider.go
  providers/providerverifier_test.go
  verifier/verifier_test.go
Labels: enhancement

#179 feat: Adds OIDC ID Token Refresh Flow to openpubkey client and google op
  client/client.go
  client/opkclient_test.go
  discover/discover.go
  examples/google/example.go
  go.mod
  go.sum
  oidc/jwt.go
  oidc/jwt_test.go
  oidc/tokens.go
  pktoken/compact.go
  pktoken/compact_test.go
  pktoken/mocks/pktoken.go
  pktoken/pktoken.go
  providers/github_actions.go
  providers/github_actions_test.go
  providers/gitlab_ci.go
  providers/gitlab_ci_test.go
  providers/google.go
  providers/google_test.go
  providers/gq_test.go
  providers/mockprovider.go
  providers/mockprovider_test.go
  providers/mocks/backend.go
  providers/mocks/backend_test.go
  providers/mocks/idtoken.go
  providers/op.go
  providers/providerverifier_test.go
  verifier/verifier.go
  verifier/verifier_test.go
Labels: enhancement

#198 bugfix: Infer signature is OIDC if type is missing from headers in `NewFromCompact`
  pktoken/pktoken.go
Labels: bug

#197 feat: Client now returns a deep copy of the PK Token it generated
  client/client.go
  client/opkclient_test.go
  pktoken/pktoken.go
  pktoken/pktoken_test.go
Labels: enhancement
