Repository openpubkey/openpubkey, pull requests merged in 2025-02, with the labels that each got.

#220 Creates web chooser for selecting OP to use in client
  client/choosers/chooser.tmpl
  client/choosers/static/buttons/azure-dark.svg
  client/choosers/static/buttons/azure-light.svg
  client/choosers/static/buttons/google-dark.svg
  client/choosers/static/buttons/google-light.svg
  client/choosers/web_chooser.go
  client/choosers/web_chooser_test.go
  client/client.go
  examples/google/example.go
  examples/web/example.go
  go.mod
  providers/azure.go
  providers/google.go
  providers/op.go
  providers/standard_provider.go
Labels: enhancement

#228 Improves test coverage on Cosigner Provider
  client/cos_test.go
  cosigner/authcosigner_test.go
Labels: tests

#231 Fixes issue where GQ library does not provide sufficient sounddness for RSA exponents that are not 65537
  gq/gq.go
  gq/gq_test.go
Labels: bug, vuln

#233 Adds expiration policy
  providers/expiration.go
  providers/expirations_test.go
  providers/github_actions.go
  providers/gitlab_ci.go
  providers/mocks/idtoken.go
  providers/providerverifier.go
  providers/providerverifier_test.go
  providers/standard_provider.go
Labels: enhancement

#237 Adds a check for whether the openssh version for opkssh is greater than 8.1. Please refer issue #215
  examples/ssh/opkssh/cli.go
  examples/ssh/opkssh/cli_test.go
Labels: enhancement

#239 Renames opk-ssh to opkssh
  opkssh/README.md
  opkssh/commands/add.go
  opkssh/commands/verify.go
  opkssh/internal/projectpath/projectpath.go
  opkssh/main.go
  opkssh/policy/enforcer.go
  opkssh/policy/fileloader.go
  opkssh/policy/policy.go
  opkssh/policy/policy_test.go
  opkssh/test/integration/add_test.go
  opkssh/test/integration/integration.go
  opkssh/test/integration/ssh_server/debian_opkssh.Dockerfile
  opkssh/test/integration/ssh_test.go
Labels: enhancement

#240 Deletes example ssh project, moves code to opkssh
  examples/ssh/opkssh/cli.go
  examples/ssh/opkssh/policy.go
  examples/ssh/opkssh/policy_test.go
  examples/ssh/sshcert/sshcert.go
  examples/ssh/sshcert/sshcert_test.go
  opkssh/commands/verify.go
  opkssh/commands/verify_test.go
  opkssh/main.go
  opkssh/main_test.go
  opkssh/sshcert/sshcert_test.go
Labels: chore

#242 Adds fresh ID Token expiration policy to verifier
  opkssh/commands/verify.go
  opkssh/commands/verify_test.go
  opkssh/main.go
  opkssh/sshcert/sshcert.go
  providers/expiration.go
  providers/expirations_test.go
  providers/github_actions.go
  providers/gitlab_ci.go
  providers/providerverifier.go
  providers/providerverifier_test.go
  providers/standard_provider.go
  verifier/expiration.go
  verifier/expiration_test.go
  verifier/verifier.go
  verifier/verifier_test.go
Labels: enhancement

#244 Azure and Google support in OPKSSH (Webchooser, Config files)
  .gitignore
  README.md
  examples/web/example.go
  opkssh/README.md
  opkssh/commands/add.go
  opkssh/commands/login.go
  opkssh/commands/verify.go
  opkssh/commands/verify_test.go
  opkssh/config/configlog.go
  opkssh/config/configlog_test.go
  opkssh/config/table.go
  opkssh/config/table_test.go
  opkssh/docs/config.md
  opkssh/main.go
  opkssh/policy/enforcer.go
  opkssh/policy/enforcer_test.go
  opkssh/policy/fileloader.go
  opkssh/policy/multiuserloader_test.go
  opkssh/policy/providerpolicy.go
  opkssh/policy/userfileloader.go
  opkssh/policy/userfileloader_test.go
  opkssh/policy/usermultifileloader.go
  opkssh/policy/userpolicy.go
  opkssh/policy/userpolicy_test.go
  opkssh/test/integration/add_test.go
  opkssh/test/integration/ssh_server/debian_opkssh.Dockerfile
  opkssh/test/integration/ssh_test.go
  pktoken/pktoken.go
  pktoken/pktoken_test.go
  verifier/verifier.go
  verifier/verifier_test.go
Labels: enhancement

#248 Adds installer to OPKSSH to get servers setup quickly
  go.mod
  go.sum
  opkssh/commands/install.go
  opkssh/docs/config.md
  opkssh/main.go
  opkssh/policy/files/configlog.go
  opkssh/policy/files/configlog_test.go
  opkssh/policy/files/table.go
  opkssh/policy/files/table_test.go
  opkssh/policy/providerpolicy.go
  opkssh/policy/userfileloader_test.go
  opkssh/policy/userpolicy.go
  opkssh/test/integration/add_test.go
Labels: enhancement

#257 Collection of fixes in opkssh for release 0.5
  opkssh/commands/install.go
  opkssh/commands/login.go
  opkssh/main.go
  opkssh/policy/enforcer.go
  opkssh/policy/enforcer_test.go
  opkssh/policy/multiuserloader_test.go
  opkssh/policy/providerpolicy_test.go
  opkssh/policy/userfileloader.go
  opkssh/policy/userfileloader_test.go
  opkssh/policy/userpolicy.go
  opkssh/policy/userpolicy_test.go
  opkssh/test/integration/add_test.go
  pktoken/pktoken.go
Labels: bug, enhancement

#258 Improves identity string
  opkssh/commands/login.go
Labels: enhancement

#260 Update google and azure clientIDs
  opkssh/commands/install.go
  opkssh/docs/config.md
  opkssh/policy/files/table_test.go
  providers/azure.go
  providers/google.go
Labels: chore

#265 Creates opkssh binary release github action workflow
  .github/workflows/release-opkssh.yml
  opkssh/main.go
Labels: enhancement

#264 Creates install script for binary installs
  opkssh/scripts/install-linux.sh
Labels: enhancement

#273 Points opkssh binary to same location
  opkssh/README.md
  opkssh/commands/install.go
  opkssh/commands/verify.go
  opkssh/docs/config.md
  opkssh/main.go
  opkssh/test/integration/add_test.go
  opkssh/test/integration/ssh_server/debian_opkssh.Dockerfile
Labels: bug
