Repository openpubkey/openpubkey, pull requests merged in 2025-04, with the labels that each got.

#311 feat: discover signing algs to support es256
  providers/standard_provider.go
Labels: enhancement

#312 test: Add test coverage for ES256
  client/opkclient_test.go
  providers/github_actions_test.go
  providers/gitlab_ci_test.go
  providers/hello.go
  providers/mockprovider.go
  providers/mocks/backend.go
  providers/mocks/backend_test.go
  providers/mocks/idtoken.go
  providers/providerverifier.go
  providers/providerverifier_test.go
  providers/standard_provider_test.go
  verifier/verifier_test.go
Labels: tests

#319 Adds link to openpubkey mailing list
  README.md
Labels: documentation, chore

#322 Fixes minor typo in docs/idtokens.md
  docs/idtokens.md
Labels: bug, documentation, chore

#324 Fixes web chooser test that was breaking due to resolving example.com
  client/choosers/web_chooser_test.go
Labels: bug
