Repository openpubkey/openpubkey, pull requests merged in 2025-03, with the labels that each got.

#278 opkssh add creates `~/.opk/auth_id` if it doesn't exist yet
  opkssh/commands/add.go
  opkssh/policy/fileloader.go
  opkssh/policy/userfileloader.go
Labels: bug

#277 Adds Gitlab Provider to OPKSSH
  client/choosers/chooser.tmpl
  client/choosers/static/buttons/gitlab-dark.svg
  client/choosers/static/buttons/gitlab-light.svg
  client/choosers/web_chooser.go
  client/choosers/web_chooser_test.go
  opkssh/commands/install.go
  opkssh/main.go
  opkssh/policy/providerpolicy.go
  opkssh/policy/providerpolicy_test.go
  opkssh/scripts/install-linux.sh
  providers/gitlab.go
Labels: enhancement

#281 Adds toolchain directive
  go.mod
Labels: bug

#289 Switches from id_dsa as a default ssh key filename
  opkssh/commands/login.go
Labels: bug, opkssh

#282 Fix #207: Allow typ override in VerifySignedMessage with test
  pktoken/osm.go
  pktoken/osm_test.go
Labels: enhancement

#291 Reenables disabled linter checks and resolves linter problems
  .github/workflows/go.yml
  .golangci.yml
  client/choosers/web_chooser.go
  opkssh/main.go
Labels: bug

#293 Moves opkssh out of openpubkey into its own repo
  .github/workflows/ci.yml
  .github/workflows/release-opkssh.yml
  opkssh/README.md
  opkssh/commands/add.go
  opkssh/commands/login.go
  opkssh/commands/readhome_linux.go
  opkssh/commands/readhome_windows.go
  opkssh/commands/verify.go
  opkssh/commands/verify_test.go
  opkssh/docs/config.md
  opkssh/internal/projectpath/projectpath.go
  opkssh/main.go
  opkssh/main_test.go
  opkssh/policy/enforcer.go
  opkssh/policy/enforcer_test.go
  opkssh/policy/files/configlog.go
  opkssh/policy/files/configlog_test.go
  opkssh/policy/files/fileloader.go
  opkssh/policy/files/permschecker.go
  opkssh/policy/files/permschecker_test.go
  opkssh/policy/files/table.go
  opkssh/policy/files/table_test.go
  opkssh/policy/multipolicyloader.go
  opkssh/policy/multipolicyloader_test.go
  opkssh/policy/policy.go
  opkssh/policy/policy_test.go
  opkssh/policy/policyloader.go
  opkssh/policy/policyloader_test.go
  opkssh/policy/providerloader.go
  opkssh/policy/providerloader_test.go
  opkssh/scripts/install-linux.sh
  opkssh/scripts/installing.md
  opkssh/sshcert/sshcert.go
  opkssh/sshcert/sshcert_test.go
  opkssh/test/integration/add_test.go
  opkssh/test/integration/fakeop.go
  opkssh/test/integration/integration.go
  opkssh/test/integration/login_test.go
  opkssh/test/integration/opkssh_test.go
  opkssh/test/integration/provider/exampleop.Dockerfile
  opkssh/test/integration/provider/provider.go
  opkssh/test/integration/ssh_server/debian_opkssh.Dockerfile
  opkssh/test/integration/ssh_server/ssh_server.go
  opkssh/test/integration/ssh_server/ubuntu.Dockerfile
  opkssh/test/integration/ssh_test.go
Labels: chore, opkssh

#292 Fixes version of go in contribution guide
  CONTRIBUTING.md
Labels: bug

#298 bug: Fixes hanging bug that opkssh was hitting
  client/choosers/web_chooser.go
  examples/web/example.go
Labels: bug

#307 Documents hello.dev ID Token
  docs/idtokens.md
Labels: documentation

#306 Adding the possibility to use other IDPs than google, microsoft and g…
  client/choosers/chooser.tmpl
  client/choosers/web_chooser.go
  client/choosers/web_chooser_test.go
  providers/standard_provider.go
Labels: enhancement

#308 bug: Adds tells user URI to open when open browser is disabled
  client/choosers/web_chooser.go
  examples/web/example.go
  providers/standard_provider.go
Labels: bug, enhancement
